- helpers/CHANGELOG.md
- helpers/README.md
- helpers/package.json
- helpers/serializer.js
- helpers/test.js
per elastic/ecs-logging#33
I need to get this in and publish a new helpers package before completing #23
> helpers: stringify() 'log.level' as a top-level dotted field

- loggers/morgan/CHANGELOG.md
- loggers/morgan/index.js
- loggers/morgan/package.json
- loggers/morgan/test.js
- loggers/pino/CHANGELOG.md
- loggers/pino/index.js
- loggers/pino/package.json
- loggers/pino/test.js
- loggers/winston/CHANGELOG.md
- loggers/winston/index.js
- loggers/winston/package.json
- loggers/winston/test.js
Per https://github.com/elastic/ecs-logging/blob/c3567a9/spec/spec.json#L21 it
is preferred to have "log.level" as a flat top-level field.
Also, the intent of log.logger is to be the app's logger name, rather
than the name of the logging framework.
> pino: flat log.level, use "name" for log.logger

- loggers/winston/package.json
- loggers/winston/test.js
It adds coverage testing (including mandating 100% coverage with the
tap "--100" option). As well, I find that node-tap is slightly more
reliable on identifying a particular failing test when an exception
is raised.
```
% npx tap --100
PASS  test.js 13 OK 74.95ms
🌈 SUMMARY RESULTS 🌈
Suites:   1 passed, 1 of 1 completed
Asserts:  13 passed, of 13
Time:     1s
----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |      100 |      100 |      100 |      100 |                   |
index.js |      100 |      100 |      100 |      100 |                   | …
```
> winston: change from ava to tap for testing

- loggers/winston/index.js
This changes the Winston transform to use a map lookup rather than array lookup to be slightly faster in theory, and slightly (though marginally and within one stddev -- to the degree I understand the benchmarking tool's reporting):
Before:
```
% npm run bench
...
node: v14.15.4
uname: Darwin pink.local 19.6.0 Darwin Kernel Version 19.6.0: Tue Nov 10 00:10:30 PST 2020; root:xnu-6153.141.10~1/RELEASE_X86_64 x86_64
git: heads/master-0-g634210a
Warmup 5s run
Running 30s test @ http://localhost:3000
100 connections with 10 pipelining factor
┌─────────┬───────┬───────┬───────┬───────┬──────────┬─────────┬────────┐
│ Stat    │ 2.5%  │ 50%   │ 97.5% │ 99%   │ Avg      │ Stdev   │ Max    │
├─────────┼───────┼───────┼───────┼───────┼──────────┼─────────┼────────┤
│ Latency │ 34 ms │ 39 ms │ 47 ms …
```
> perf(winston): marginally faster log record building

- .github/labeler-config.yml
- .github/workflows/labeler.yml
This label is used to include issues in the APM Agents project.
> chore: add GH action to auto-label new issues/PRs with 'agent-nodejs'

- loggers/morgan/CHANGELOG.md
- loggers/morgan/index.js
- loggers/morgan/package.json
- loggers/morgan/test/apm.test.js
- loggers/morgan/test/serve-one-http-req-with-apm.js
- loggers/pino/CHANGELOG.md
- loggers/pino/index.js
- loggers/pino/package.json
- loggers/pino/test/apm.test.js
- loggers/pino/test/serve-one-http-req-with-apm.js
- loggers/pino/test/use-apm-override-service-name.js
- loggers/winston/CHANGELOG.md
- loggers/winston/index.js
- loggers/winston/package.json
- loggers/winston/test/apm.test.js
- loggers/winston/test/serve-one-http-req-with-apm.js
- loggers/winston/test/use-apm-override-service-name.js
Set "service.name" and "event.dataset" log fields if Elastic APM is started.
This helps to filter for different log streams in the same pod and the
latter is required for log anomaly detection.
> feat: set "service.name" and "event.dataset" from APM

- helpers/CHANGELOG.md
- helpers/README.md
- helpers/lib/error-formatters.js
- helpers/lib/index.js
- helpers/lib/serializer.js
- helpers/test.js
This adds `formatError(ecsFields, err)` that will be used to add ECS Error fields (https://www.elastic.co/guide/en/ecs/current/ecs-error.html) to log records.
> feat: add helpers.formatError for serializing ECS error fields

- loggers/morgan/test/apm.test.js
- loggers/pino/test/apm.test.js
- loggers/winston/test/apm.test.js
If we lost the race we would end up waiting on app.on('close') that had
already fired.
Fixes: #46
> tests: fix race in apm tracing tests

- docs/morgan.asciidoc
- docs/pino.asciidoc
- docs/winston.asciidoc
- loggers/morgan/CHANGELOG.md
- loggers/morgan/index.js
- loggers/morgan/test/apm.test.js
- loggers/morgan/test/basic.test.js
- loggers/morgan/test/serve-one-http-req-with-apm.js
- loggers/pino/CHANGELOG.md
- loggers/pino/index.js
- loggers/pino/test/apm.test.js
- loggers/pino/test/serve-one-http-req-with-apm.js
- loggers/winston/CHANGELOG.md
- loggers/winston/index.js
- loggers/winston/test/apm.test.js
- loggers/winston/test/serve-one-http-req-with-apm.js
This also changes the argument to the `@elastic/ecs-morgan-format` export to prefer to take an options object.
The old call signature is still supported for backward compat.
Refs: #60
> feat: add 'apmIntegration: false' option to disable Elastic APM integration

- loggers/pino/CHANGELOG.md
- loggers/pino/index.js
- loggers/pino/test/apm.test.js
- loggers/pino/test/basic.test.js
- loggers/pino/test/use-apm-override-service-name.js
The 'base' option to pino allows one to change (or null out) the
default "bindings". ecs-format-pino wasn't handling (a) a changed
base, nor (b) `base: null` which results in `formatters.bindings()`
not being called by pino at all -- which broke addition of
"ecs.version", "service.name", and "event.dataset".
> fix: usage of 'base' option to pino constructor

- helpers/CHANGELOG.md
- helpers/README.md
- helpers/lib/error-formatters.js
- helpers/lib/http-formatters.js
- helpers/test/basic.test.js
- helpers/test/express.test.js
- helpers/test/hapi.test.js
This also changes those and formatError to return a bool for whether the
given obj was processed. The loggers will be able to use this to control
passing through an unprocessed special field.
Refs: #58
> fix(helpers): make formatHttpRequest and formatHttpResponse more defensive

- loggers/morgan/CHANGELOG.md
- loggers/morgan/package.json
- loggers/pino/CHANGELOG.md
- loggers/pino/package.json
- loggers/winston/CHANGELOG.md
- loggers/winston/index.js
- loggers/winston/package.json
- loggers/winston/test/apm.test.js
- loggers/winston/test/use-apm-override-service-name.js
Fix a couple crashes with convertReqRes:true and logging a req/res that
isn't an HTTP request or response object -- via update to ecs-helpers v1.1.0.
Also fix some conflicts with logging top-level "event" and "service"
fields with the winston formatter.
Fixes: #58
Fixes: #59
> fix(winston, pino): a few crashes with req, res, event, and service fields

- utils/ecs-logging/spec.json
ECS logging specs automatic sync
* * *
Update: This was for this change: Allow "message" field to be excluded (https://github.com/elastic/ecs-logging/pull/55)
> synchronize ecs-logging spec

- loggers/pino/CHANGELOG.md
- loggers/pino/index.js
- loggers/pino/test/basic.test.js
Now that "message" is optional in the ecs-logging spec, we can drop
the fallback to an empty string message added in #64.
Fixes: #73
> fix (pino): do not fallback to empty string "message" if none given

- loggers/pino/CHANGELOG.md
- loggers/pino/index.js
Now that elastic-apm-node uses this package for its own logging.
Fixes: #79
> fix(pino): avoid circular-require between this and elastic-apm-node

- .gitignore
- loggers/pino/test/apm.test.js
- loggers/winston/test/apm.test.js
The APM tests for the Winston and Pino formatters started failing with
the release of elastic-apm-node@3.16.0, because it included changes that
could lead to the order of APM reported "transaction" and "span" objects
being reverse (in this case because span encoding is now faster). This
changes the test code to not be subject to that order race.
> tests: fix APM tests for elastic-apm-node@3.16.0

- loggers/pino/CHANGELOG.md
- loggers/pino/index.js
- loggers/pino/package.json
Expected usage in APM agent tests is something like:
```
const apm = require('../..')  // note the import path is not "elastic-apm-node"
const log = pino(ecsFormat({ _elasticApm: apm }))
// ...
```
This allows the APM agent tests to use the local APM agent working copy to test APM tracing integration in the logger.
This is going to be used to test https://github.com/elastic/apm-agent-nodejs/pull/2127
> feat: add internal/testing-only opts._elasticApm to facilitate APM agent tests

- loggers/winston/index.d.ts
- loggers/winston/package.json
This is essentially the same as the Pino PR https://github.com/elastic/ecs-logging-nodejs/pull/82 .
For: https://github.com/elastic/ecs-logging-nodejs/issues/77 .
> feat(winston): add TS types

- loggers/pino/CHANGELOG.md
- loggers/pino/package.json
- loggers/winston/CHANGELOG.md
- loggers/winston/package.json
1.3.0 release of pino and winston to get TypeScript types released.
> @elastic/ecs-pino-format@1.3.0, @elastic/ecs-winston-format@1.3.0

- loggers/winston/index.d.ts
> fix(ecs-winston-format): fix expression in ambient context error

- loggers/winston/CHANGELOG.md
- loggers/winston/package.json
A release to get https://github.com/elastic/ecs-logging-nodejs/pull/93 out.
> @elastic/ecs-winston-format@1.3.1

- docs/intro.asciidoc
This adds a link to a new [Node.JS ECS logging tutorial](https://www.elastic.co/guide/en/cloud/current/ec-getting-started-search-use-cases-node-logs.html) in the Cloud docs.
@bmorelli25, or anyone, please let me know if you think there might be a better place for this link.
> Add a link to the Node.js ECS logging tutorial in the Cloud docs

- docs/winston.asciidoc
Rel: #99 
Adds a link at the bottom of this [Node.js winston ECS logging page](https://www.elastic.co/guide/en/ecs-logging/nodejs/master/winston.html#_setup_3) to a [similar tutorial](https://www.elastic.co/guide/en/cloud/current/ec-getting-started-search-use-cases-node-logs.html) in the Cloud docs.
> Add a link from winston ECS logging to a Cloud tutorial doc

- loggers/pino/test/apm.test.js
- loggers/pino/test/serve-one-http-req-with-apm.js
- loggers/winston/index.js
- loggers/winston/test/apm.test.js
- loggers/winston/test/serve-one-http-req-with-apm.js
Two changes in elastic-apm-node@3.24.0 impacted tests here:
- "Zero configuration support" changed how the APM serviceName is
handled for edge cases.
- Run context handling changes made it so `span.end()` actually removes
the span from the current context, so log records after span.end() no
longer have that span.id.
> tests: update APM-related tests for zero-conf and run-context changes

- loggers/morgan/test/serve-one-http-req-with-apm.js
- loggers/pino/test/serve-one-http-req-with-apm.js
- loggers/winston/test/serve-one-http-req-with-apm.js
In elastic-apm-node@3.28.0 (https://github.com/elastic/apm-agent-nodejs/pull/2546)
the APM agent added a default request to "GET /" of the APM server to
determine its version. This broke tests here.
This fixes test failures such as these ones:
https://apm-ci.elastic.co/job/apm-agent-nodejs/job/ecs-logging-nodejs-mbp/job/main/5/
```
13:47:54  > @elastic/ecs-winston-format@1.3.1 test /var/lib/jenkins/workspace/dejs_ecs-logging-nodejs-mbp_main/src/go.elastic.co/apm/ecs-logging-nodejs/loggers/winston
13:47:54  > standard && tap --timeout ${TAP_TIMEOUT:-10} test/*.test.js
13:47:54  
13:47:57  TAP version 13
13:52:57  # Subtest: test/apm.test.js
13:52:57      # Subtest: tracing integration works
13:52:57          ok 1 - no error from starting the mock APM server
13:52:57          ok 2 - …
```
> tests: fix apm-integration tests failures due to newer agent making APM server version check

- loggers/morgan/test/serve-one-http-req-with-apm.js
- loggers/pino/test/serve-one-http-req-with-apm.js
- loggers/winston/test/serve-one-http-req-with-apm.js
Since elastic-apm-node@3.47.0 the APM agent will log.info a preamble with config and some other basic debugging info. This was breaking the APM-related tests.
> tests: fix tests to work with recent elastic-apm-node that includes a log preamble

- .ci/run-install.sh
- .ci/run-lint.sh
- .github/workflows/test.yml
- Makefile
- helpers/package.json
- loggers/morgan/package.json
- loggers/pino/package.json
- loggers/winston/package.json
- utils/package.json
- utils/pre-commit-hook.sh
Also test with node v20 instead of v19.
> chore: separate 'lint' from 'test'

- helpers/README.md
- helpers/test/basic.test.js
- loggers/pino/README.md
Changes in #150 missed these. Then the subsequent spec update (#135)
resulted in tests being broken by those missing cases.
> fix: update remaining cases where `ecs.version` was not a top-level field

- docs/morgan.asciidoc
- docs/pino.asciidoc
- docs/winston.asciidoc
- loggers/morgan/CHANGELOG.md
- loggers/morgan/README.md
- loggers/morgan/index.js
- loggers/morgan/test/apm.test.js
- loggers/morgan/test/basic.test.js
- loggers/morgan/test/serve-one-http-req-with-apm.js
- loggers/pino/CHANGELOG.md
- loggers/pino/README.md
- loggers/pino/index.d.ts
- loggers/pino/index.js
- loggers/pino/test/apm.test.js
- loggers/pino/test/basic.test.js
- loggers/pino/test/serve-one-http-req-with-apm.js
- loggers/winston/CHANGELOG.md
- loggers/winston/README.md
- loggers/winston/index.d.ts
- loggers/winston/index.js
- loggers/winston/test/apm.test.js
- loggers/winston/test/basic.test.js
- loggers/winston/test/serve-one-http-req-with-apm.js
These are retrieved from an active APM agent, if apmIntegration is
enabled. As well, config options for overriding these (and service.name)
have been added.
Closes: #121
Closes: #87
Refs: https://github.com/elastic/apm-agent-nodejs/issues/3195
> feat: more correlation fields: service.version, service.environment, service.node.name

- packages/ecs-winston-format/CHANGELOG.md
- packages/ecs-winston-format/index.js
- packages/ecs-winston-format/package.json
- packages/ecs-winston-format/test/basic.test.js
- packages/ecs-winston-format/test/errors.test.js
- packages/ecs-winston-format/test/uncaught-exception.js
- packages/ecs-winston-format/test/unhandled-rejection.js
- packages/ecs-winston-format/test/utils.js
This handles the various ways an Error instance can be passed
to a Winston logger, and serializes those Errors to 'error.*'
fields.
Closes: https://github.com/elastic/ecs-logging-nodejs/issues/128
> feat(winston): improve serialization of Error instances

- .github/workflows/tav.yml
- Makefile
- docs/pino.asciidoc
- docs/winston.asciidoc
- packages/ecs-pino-format/.tav.yml
- packages/ecs-pino-format/README.md
- packages/ecs-pino-format/package.json
- packages/ecs-pino-format/test/basic.test.js
- packages/ecs-winston-format/.tav.yml
- packages/ecs-winston-format/README.md
- packages/ecs-winston-format/package.json
We support pino@6, pino@7, pino@8, and winston@3.
Refs: https://github.com/elastic/ecs-logging-nodejs/pull/131
Refs: https://github.com/elastic/ecs-logging-nodejs/issues/115
---
This adds "TAV" (test-all-versions) tests to test against supported versions of pino and winston. I didn't bother with morgan because there hasn't been a new release of it for years.  CI is setup to run this once per week.
> test: add TAV tests for pino and winston supported versions

- docs/winston.asciidoc
- packages/ecs-winston-format/.tav.yml
- packages/ecs-winston-format/package.json
The version specifier was originally 3.3.3 and now I wonder if that
was for a good reason. While attempting to TAV test with node v14
I get timeouts attempting to install winston@3.3.1.
> test: fix winston TAV tests, raise min-supported Winston to 3.3.3

- docs/intro.asciidoc
- docs/morgan.asciidoc
- docs/pino.asciidoc
- docs/winston.asciidoc
- packages/ecs-helpers/CHANGELOG.md
- packages/ecs-helpers/lib/http-formatters.js
- packages/ecs-helpers/lib/index.js
- packages/ecs-helpers/package.json
- packages/ecs-helpers/test/express.test.js
- packages/ecs-helpers/test/hapi.test.js
- packages/ecs-morgan-format/CHANGELOG.md
- packages/ecs-morgan-format/README.md
- packages/ecs-pino-format/CHANGELOG.md
- packages/ecs-pino-format/README.md
- packages/ecs-pino-format/package.json
- packages/ecs-winston-format/CHANGELOG.md
- packages/ecs-winston-format/README.md
Closes: https://github.com/elastic/ecs-logging-nodejs/issues/133
Closes: https://github.com/elastic/ecs-logging-nodejs/issues/76
> feat: add 'http.request.id' field, @elastic/ecs-helpers@2.1.0, bump ecs.version to 8.10.0

- packages/ecs-morgan-format/package.json
- packages/ecs-winston-format/package.json
- utils/create-schema.js
- utils/schema.json
- update the ecs-helpers deps for morgan and winston
- update the ECS JSON schema (and the generation script) from ecs.git v8.10.0 tag
Refs: #163
---
I missed a couple things in the ECS version update in #163. The JSON schema was regenerated from tag "v8.10.0" from elastic/ecs.git. This JSON schema is used in tests to validate created log records.
> chore: some missing parts of the ECS schema version update

- packages/ecs-helpers/CHANGELOG.md
- packages/ecs-helpers/lib/http-formatters.js
- packages/ecs-helpers/test/express.test.js
Use `req.originalUrl`, if available, when converting `req` to ECS fields.
This is necessary because Express, and possibly Fastify, will mutate req.url
during routing in some cases.
Fixes: https://github.com/elastic/ecs-logging-nodejs/issues/114
> fix: use req.originalUrl (express, fastify)

- packages/ecs-morgan-format/package.json
fixes #169
Added missing index.d.ts file in package.json files property so it will be added in next release.
> fixes: #169 Add missing d.ts file in ecs-morgan-format

- packages/ecs-pino-format/examples/express-with-pino-http.js
This tries to better mimic pino-http's express usage example
https://github.com/pinojs/pino-http#use-as-express-middleware
and points to a user-provided gist configuring pino to
work past this 'req' field limitation.
> docs: minor tweak to pino-http example

- docs/winston.asciidoc
- packages/ecs-winston-format/CHANGELOG.md
- packages/ecs-winston-format/index.js
- packages/ecs-winston-format/test/basic.test.js
Winston's logform docs state that 'info' objects should always
have 'level' and 'message' fields. Some downstream transforms
and transports can rely on this. Instead the 'ecsStringify' will
handle excluding the 'level' field from the stringification.
Closes: #173
> fix(winston): do not remove info.level field

- .github/workflows/addToProject.yml
- .github/workflows/labeler.yml
⚠️ This PR was created by an automated tool. Please review the changes carefully. ⚠️ 
We want to set the default permissions for workflows to read-only for contents. 
This is a security measure to prevent accidental changes to the repository.
This change adds a top-level permissions block to all workflows in the .github/workflows directory.
```yaml
permissions:
contents: read
```
In some cases workflows might need more permissions than just `contents: read`.
Please checkout this branch and add the necessary permissions to the workflows.
If your workflow uses a Personal Access Token (PAT), we can still add the permissions block,
but it will not have any effect.
Merging this PR as is might cause workflows that need more permissions to fail.
If there are any questions, please reach out to …
> security: add permissions block to workflows

- packages/ecs-winston-format/CHANGELOG.md
- packages/ecs-winston-format/index.js
- packages/ecs-winston-format/package.json
- packages/ecs-winston-format/test/errors.test.js
In winston@3.12.0, the handling of unhandledRejection events changed
slightly: setting '<record>.rejection=true` rather than `<record>.exception`.
* * *
This changed in https://github.com/winstonjs/winston/pull/2390.
This is the reason for the CI failures seen on the unrelated https://github.com/elastic/ecs-logging-nodejs/pull/180 PR.
I will do a v1.5.3 release for  this.
> fix(winston): fix unhandledRejection handling for winston@3.12.0 changes; release @elastic/ecs-winston-format@1.5.3

- .github/community-label.yml
- .github/labeler-config.yml
- .github/workflows/addToProject.yml
- .github/workflows/labeler.yml
These are based on the current actions in apm-agent-nodejs.git.
> chore: update CI actions for project assigning and labeling

- .github/actions/npm-publish/action.yml
- .github/workflows/release-ecs-helpers.yml
- .github/workflows/release.yml
- RELEASING.md
- packages/ecs-helpers/package.json
- packages/ecs-morgan-format/package.json
- packages/ecs-pino-format/package.json
- packages/ecs-winston-format/package.json
I took some of the changes done in https://github.com/elastic/elastic-otel-node/pull/138
and enable the automation to release through Github workflows using a service machine account.
I also created two different workflows:
- the one supporting the ecs-helpers package
- the other one supporting the other packages.
> release: automate the release for this project

- docs/reference/index.md
- docs/reference/morgan.md
- docs/reference/pino.md
- docs/reference/winston.md
Follow up to #206 
When using cross-repo links, the path should be relative to the `docset.yml` not the full path within the repo ([updated docs-builder docs](https://elastic.github.io/docs-builder/syntax/links/#cross-repository-links)).
> [docs] Clean up cross-repo links
